// igna-chat.js — Generated by NJ Civic AI Exchange
// Site: __SITE_IDENTIFIER__ | Pages indexed: __PAGES_INDEXED__
// Add this file to your website before the </body> tag.
(function () {
  var IGNA_CONFIG = {
    apiKey: "__API_KEY__",
    siteIdentifier: "__SITE_IDENTIFIER__",
    kbIdentifier: "__KB_IDENTIFIER__",
    pagesIndexed: __PAGES_INDEXED__,
    backendUrl: "__BACKEND_URL__",
    theme: {
      primaryColor: "__PRIMARY_COLOR__",
      accentColor: "__ACCENT_COLOR__"
    }
  };

  var s = document.createElement("script");
  s.src = IGNA_CONFIG.backendUrl + "/widget/igna-chat-widget.js";
  s.async = true;
  s.onload = function () {
    if (window.IGNAChat) {
      window.IGNAChat.init(IGNA_CONFIG);
    }
  };
  document.head.appendChild(s);
})();
